--- 
id: continue
base_name: continue
tags: []

presentation_date: 
version: 1.0.0
licenses: []

slideshare_id: 
speaker_deck_id: 
author: 
  markup_language: :rd
  name: Yutaro Sugai
  email: y.sugai@everyleaf.com
  rubygems_user: hokkai7go
  slideshare_user: hokkai7go
  speaker_deck_user: 
