--- 
id: shinjukurb
base_name: shinjukurb
tags: []

presentation_date: 
version: 1.0.0
licenses: []

slideshare_id: 
speaker_deck_id: 
author: 
  markup_language: :rd
  name: hokkai7go
  email: hokkai7go@gmail.com
  rubygems_user: hokkai7go
  slideshare_user: hokkai7go
  speaker_deck_user: 
